module.exports = [
  {
    "title": "Blender",
    "slug": "blender",
    "url": "/blender.html",
    "group": "Kitchen",
    "cardTitle": "The blender that makes the most sense",
    "decision": "Vitamix 5200",
    "image": "/Vitamix_5200.png",
    "imageAlt": "Vitamix 5200",
    "summary": "The best blender for most people: proven long-term durability, consistent blending across hard use cases, and a simple design with fewer failure points.",
    "proof": "avoids the replacement cycle better than cheaper and more feature-heavy blenders.",
    "price": "Typical price: $350–$480",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $350–$480",
    "featuredQuote": "“The best blender for most people: Vitamix 5200 — proven durability, consistent performance, and simple long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> proven motor durability, consistent results across smoothies, frozen fruit, nut butters, and soups, and a simple low-failure design."
  },
  {
    "title": "Air Fryer",
    "slug": "air-fryer",
    "url": "/air-fryer.html",
    "group": "Kitchen",
    "cardTitle": "The air fryer most kitchens should buy",
    "decision": "Instant Vortex Plus 6-Quart Air Fryer with ClearCook",
    "image": "/Instant_Vortex_Plus__transparent_.png",
    "imageAlt": "Instant Vortex Plus 6-Quart Air Fryer with ClearCook",
    "summary": "The best air fryer for most people: practical 6-quart capacity, strong everyday performance, and fewer tradeoffs than oversized, dual-basket, or ultra-cheap options.",
    "proof": "the 6-quart ClearCook model hits the sweet spot for daily cooking without overbuying capacity or features.",
    "price": "Typical price: $90–$150",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $90–$150",
    "featuredQuote": "“The best air fryer for most people: Instant Vortex Plus 6-Quart Air Fryer with ClearCook — practical capacity, strong everyday cooking, and simpler long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> the 6-quart ClearCook model hits the sweet spot for daily meals without paying for features most households ignore."
  },
  {
    "title": "Coffee Grinder",
    "slug": "coffee-grinder",
    "url": "/coffee-grinder.html",
    "group": "Kitchen",
    "cardTitle": "The coffee grinder that makes the most sense",
    "decision": "Breville Smart Grinder Pro",
    "image": "/Breville-Smart-Grinder-Pro.png",
    "imageAlt": "Breville Smart Grinder Pro",
    "summary": "The best coffee grinder for most people: broad grind coverage, intuitive controls, and a cleaner mainstream ownership fit than cheaper or more specialized grinders.",
    "proof": "covers espresso, drip, pour-over, French press, and cold brew without pushing most buyers into specialist grinder complexity.",
    "price": "Typical price: $200–$250",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $200–$250",
    "featuredQuote": "“The best coffee grinder for most people: Breville Smart Grinder Pro — broad grind coverage, intuitive controls, and a cleaner mainstream buying path.”",
    "featuredProof": "<strong>Why it wins:</strong> broad espresso-to-French-press coverage, clear daily controls, strong mainstream availability, and fewer purchase-path regrets than harder-to-buy alternatives."
  },

  {
    "title": "Espresso Machine",
    "slug": "espresso-machine",
    "url": "/espresso-machine.html",
    "group": "Kitchen",
    "cardTitle": "The espresso machine that makes the most sense",
    "decision": "Breville Bambino Plus",
    "image": "/Bambino_Plus.png",
    "imageAlt": "Breville Bambino Plus espresso machine",
    "summary": "The best espresso machine for most people: real espresso and milk drinks, fast daily use, compact size, and fewer long-term compromises than all-in-one grinder machines.",
    "proof": "strong daily usability, a forgiving milk workflow, and no built-in grinder dependency make it the cleanest mainstream decision.",
    "price": "Typical price: $400–$500",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $400–$500",
    "featuredQuote": "“The best espresso machine for most people: Breville Bambino Plus — real espresso, easy milk drinks, compact ownership, and fewer long-term compromises.”",
    "featuredProof": "<strong>Why it wins:</strong> strong daily usability, automatic milk support, compact size, and no built-in grinder dependency."
  },

  {
    "title": "Toaster Oven",
    "slug": "toaster-oven",
    "url": "/toaster-oven.html",
    "group": "Kitchen",
    "cardTitle": "The toaster oven that makes the most sense",
    "decision": "Breville Smart Oven Pro",
    "image": "/Breville-SmartOven-Pro.png",
    "imageAlt": "Breville Smart Oven Pro toaster oven",
    "summary": "The best toaster oven for most people: consistent everyday cooking, useful capacity, intuitive controls, and a cleaner buying path than harder-to-find alternatives.",
    "proof": "balances toast, reheating, baking, broiling, and small meals without forcing buyers into oversized air-fryer ovens.",
    "price": "Typical price: $250–$350",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $250–$350",
    "featuredQuote": "“The best toaster oven for most people: Breville Smart Oven Pro — consistent cooking, useful capacity, intuitive controls, and a cleaner buying path.”",
    "featuredProof": "<strong>Why it wins:</strong> the strongest mainstream balance of cooking consistency, useful capacity, controls, availability, and long-term ownership confidence."
  },
  {
    "title": "Rice Cooker",
    "slug": "rice-cooker",
    "url": "/rice-cooker.html",
    "group": "Kitchen",
    "cardTitle": "The rice cooker that makes the most sense",
    "decision": "Zojirushi NS-ZCC10 Neuro Fuzzy",
    "image": "/Zojirushi-Overall-Best.png",
    "imageAlt": "Zojirushi NS-ZCC10 Neuro Fuzzy rice cooker",
    "summary": "The best rice cooker for most people: proven long-term reliability, forgiving rice consistency, and fewer regrets than cheap basic cookers or premium overkill.",
    "proof": "balances rice quality, keep-warm performance, usability, and long-term ownership better than cheaper or more complex alternatives.",
    "price": "Typical price: $230–$320",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $230–$320",
    "featuredQuote": "“The best rice cooker for most people: Zojirushi NS-ZCC10 Neuro Fuzzy — reliable, forgiving, and easier to defend than cheap cookers or premium overkill.”",
    "featuredProof": "<strong>Why it wins:</strong> the strongest ownership pattern, forgiving fuzzy logic, practical 5.5-cup capacity, and fewer long-term regrets than cheaper or more complex models."
  },

  {
    "title": "Food Processor",
    "slug": "food-processor",
    "url": "/food-processor.html",
    "group": "Kitchen",
    "cardTitle": "The food processor that makes the most sense",
    "decision": "Cuisinart Custom 14-Cup",
    "image": "/Cuisinart-Custom-14Cup.png",
    "imageAlt": "Cuisinart Custom 14-Cup Food Processor",
    "summary": "The best food processor for most people: proven full-size reliability, practical 14-cup capacity, and simpler ownership than cheap or feature-heavy alternatives.",
    "proof": "handles the core prep jobs most people actually repeat without forcing buyers into accessory clutter or premium overkill.",
    "price": "Typical price: $200–$320",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $200–$320",
    "featuredQuote": "“The best food processor for most people: Cuisinart Custom 14-Cup — proven, practical, and easier to defend than cheap or overbuilt alternatives.”",
    "featuredProof": "<strong>Why it wins:</strong> long-term owner trust, useful 14-cup capacity, simple controls, and fewer regret points than mini, budget, or attachment-heavy machines."
  },

  {
    "title": "Electric Kettle",
    "slug": "electric-kettle",
    "url": "/electric-kettle.html",
    "group": "Kitchen",
    "cardTitle": "The electric kettle that makes the most sense",
    "decision": "Cuisinart PerfecTemp Electric Kettle",
    "image": "/Cuisinart-PerfectTemp.png",
    "imageAlt": "Cuisinart PerfecTemp electric kettle",
    "summary": "The best electric kettle for most people: useful temperature presets, proven everyday usability, broad North American availability, and fewer regrets than niche or design-first alternatives.",
    "proof": "balances reliability, tea-friendly controls, simple daily use, and realistic availability better than prettier or more specialized kettles.",
    "price": "Typical price: $80–$130",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $80–$130",
    "featuredQuote": "“The best electric kettle for most people: Cuisinart PerfecTemp Electric Kettle — reliable presets, broad availability, and simple daily ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> useful temperature presets, a long ownership track record, simple daily controls, and a cleaner North America-wide buying path."
  },
  {
    "title": "Robot Vacuum",
    "slug": "robot-vacuum",
    "url": "/robot-vacuum.html",
    "group": "Home Essentials",
    "cardTitle": "The robot vacuum that best balances cleaning and ownership",
    "decision": "Roborock Qrevo Curv",
    "image": "/ROBOROCK_QREVO_TRANSPARENT_FOR_NOTION.png",
    "imageAlt": "Roborock Qrevo Curv",
    "summary": "The best robot vacuum for most people: reliable vacuuming, useful mopping, self-emptying convenience, and dock automation that still feels manageable.",
    "proof": "balances reliable vacuuming, useful mopping, self-emptying convenience, and ownership complexity better than most flashier alternatives.",
    "price": "Typical price: $850–$1,200",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $850–$1,200",
    "featuredQuote": "“The best robot vacuum for most people: Roborock Qrevo Curv — reliable vacuuming, useful mopping, and dock automation without overcomplicating ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> it balances reliable vacuuming, useful mopping, self-emptying convenience, and manageable ownership complexity."
  },
  {
    "title": "Air Purifier",
    "slug": "air-purifier",
    "url": "/air-purifier.html",
    "group": "Home Essentials",
    "cardTitle": "The air purifier that makes the most sense",
    "decision": "Coway AP-1512HH Mighty",
    "image": "/coway-air-purifier.png",
    "imageAlt": "Coway AP-1512HH Mighty",
    "summary": "The best air purifier for most people: real airflow for everyday rooms, reasonable filter costs, and fewer long-term tradeoffs than feature-heavy alternatives.",
    "proof": "balanced airflow, realistic room coverage, and filter costs that stay manageable over time.",
    "price": "Typical price: $180–$250",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $180–$250",
    "featuredQuote": "“The best air purifier for most people: Coway AP-1512HH Mighty — real airflow, manageable filter costs, and dependable everyday ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> balanced airflow, realistic room coverage, and filter costs that stay manageable over time."
  },
  {
    "title": "Video Doorbell",
    "slug": "video-doorbell",
    "url": "/video-doorbell.html",
    "group": "Home Essentials",
    "cardTitle": "The video doorbell that makes the most sense",
    "decision": "Ring Battery Doorbell Plus (2nd Gen)",
    "image": "/ring_battery_doorbell_plus.png",
    "imageAlt": "Ring Battery Doorbell Plus (2nd Gen)",
    "summary": "The best video doorbell for most people: easy installation, reliable alerts, strong app experience, and a removable battery that makes ownership less annoying.",
    "proof": "solves the mainstream ownership problem better than cheaper or more technical alternatives.",
    "price": "Typical price: $150–$180",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $150–$180",
    "featuredQuote": "“The best video doorbell for most people: Ring Battery Doorbell Plus (2nd Gen) — easy setup, reliable alerts, and less annoying long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> strong mainstream reliability, a removable battery, good package visibility, and a mature app ecosystem."
  },

  {
    "title": "Cordless Vacuum",
    "slug": "cordless-vacuum",
    "url": "/cordless-vacuum.html",
    "group": "Home Essentials",
    "cardTitle": "The cordless vacuum that makes the most sense",
    "decision": "Dyson V15 Detect Plus",
    "image": "/Dyson-V15.png",
    "imageAlt": "Dyson V15 Detect Plus cordless vacuum",
    "summary": "The best cordless vacuum for most people: strong mixed-floor cleaning, proven pet-hair performance, and a mature ownership case without paying for newer flagship complexity.",
    "proof": "balances cleaning power, pet-hair handling, usability, and long-term confidence better than cheaper, weaker, or newer alternatives.",
    "price": "Typical price: $600–$750",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $600–$750",
    "featuredQuote": "“The best cordless vacuum for most people: Dyson V15 Detect Plus — strong mixed-floor cleaning, pet-hair confidence, and proven ownership without flagship overkill.”",
    "featuredProof": "<strong>Why it wins:</strong> broad cleaning performance, strong pet-hair pickup, mature accessory support, and fewer unknowns than newer dock-based or flagship models."
  },
  {
    "title": "Upright Vacuum",
    "slug": "upright-vacuum",
    "url": "/upright-vacuum.html",
    "group": "Home Essentials",
    "cardTitle": "The upright vacuum that makes the most sense",
    "decision": "Shark Stratos Upright Vacuum",
    "image": "/Shark-Stratos-Upright.png",
    "imageAlt": "Shark Stratos Upright Vacuum",
    "summary": "The best upright vacuum for most people: stronger carpet cleaning, pet-hair confidence, and whole-home usability without specialty-vacuum pricing.",
    "proof": "balances carpet performance, hair control, sealed filtration, and practical ownership better than heavier or cheaper alternatives.",
    "price": "Typical price: $300–$550",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $300–$550",
    "featuredQuote": "“The best upright vacuum for most people: Shark Stratos Upright Vacuum — serious carpet cleaning, pet-hair confidence, and practical whole-home ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> strong mainstream cleaning, better hair handling, lift-away versatility, and a more defensible ownership fit than heavier or cheaper alternatives."
  },

  {
    "title": "Dehumidifier",
    "slug": "dehumidifier",
    "url": "/dehumidifier.html",
    "group": "Home Essentials",
    "cardTitle": "The dehumidifier that makes the most sense",
    "decision": "Midea Cube 50 Pint",
    "image": "/Midea-Cute-50-Pint.png",
    "imageAlt": "Midea Cube 50 Pint dehumidifier",
    "summary": "The best dehumidifier for most people: serious moisture removal, a large tank, simple drainage, and fewer long-term regrets than tiny units or pump-first alternatives.",
    "proof": "handles real household humidity without forcing most buyers into pump complexity or commercial pricing.",
    "price": "Typical price: $230–$330",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $230–$330",
    "featuredQuote": "“The best dehumidifier for most people: Midea Cube 50 Pint — serious moisture removal, easier daily ownership, and no unnecessary pump complexity.”",
    "featuredProof": "<strong>Why it wins:</strong> strong moisture removal, a large tank, continuous drainage, and a simpler reliability profile than pump-heavy or underpowered alternatives."
  },

  {
    "title": "Humidifier",
    "slug": "humidifier",
    "url": "/humidifier.html",
    "group": "Home Essentials",
    "cardTitle": "The humidifier that makes the most sense",
    "decision": "Levoit Classic 300S",
    "image": "/Levoit-Classic-300S.png",
    "imageAlt": "Levoit Classic 300S humidifier",
    "summary": "The best humidifier for most people: quiet bedroom-friendly use, easy top-fill ownership, realistic tank capacity, and fewer regrets than tiny budget units or oversized large-room machines.",
    "proof": "balances daily comfort, refill convenience, cleaning burden, and availability better than mist-heavy or feature-first alternatives.",
    "price": "Typical price: $80–$130",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $80–$130",
    "featuredQuote": "“The best humidifier for most people: Levoit Classic 300S — quiet, easy to refill, and sized for normal rooms without overbuying.”",
    "featuredProof": "<strong>Why it wins:</strong> the strongest mainstream balance of quiet use, top-fill convenience, realistic capacity, and long-term ownership simplicity."
  },


  {
    "title": "Water Flosser",
    "slug": "water-flosser",
    "url": "/water-flosser.html",
    "group": "Personal Care",
    "cardTitle": "The water flosser that makes the most sense",
    "decision": "Waterpik Aquarius Water Flosser",
    "image": "/Waterpik-Aquarius.png",
    "imageAlt": "Waterpik Aquarius Water Flosser",
    "summary": "The best water flosser for most people: reliable daily cleaning, a full-size tank, easy tip replacement, and fewer compromises than cordless or cheap high-spec alternatives.",
    "proof": "solves the real ownership problem: enough tank capacity, pressure control, and a proven tip ecosystem without battery or tiny-reservoir friction.",
    "price": "Typical price: $70–$110",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $70–$110",
    "featuredQuote": "“The best water flosser for most people: Waterpik Aquarius Water Flosser — reliable daily cleaning, a full-size tank, and fewer compromises than cordless alternatives.”",
    "featuredProof": "<strong>Why it wins:</strong> proven Waterpik ownership patterns, practical tank size, broad tip support, and a simpler long-term reliability case than battery-powered or cheap clone models."
  },

  {
    "title": "Beard Trimmer",
    "slug": "beard-trimmer",
    "url": "/beard-trimmer.html",
    "group": "Personal Care",
    "cardTitle": "The beard trimmer that makes the most sense",
    "decision": "Philips Norelco Multigroom 9000",
    "image": "/Philips-Norelco-Multigroom-9000.png",
    "imageAlt": "Philips Norelco Multigroom 9000",
    "summary": "The best beard trimmer for most people: dependable trimming, strong battery life, useful attachments, and easier long-term ownership than cheap kits or barber-style tools.",
    "proof": "solves the real ownership problem: clean repeatable beard maintenance without weak batteries, flimsy guards, or attachment clutter.",
    "price": "Typical price: $80–$130",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $80–$130",
    "featuredQuote": "“The best beard trimmer for most people: Philips Norelco Multigroom 9000 — reliable, versatile, and easier to live with than cheap kits or pro-style tools.”",
    "featuredProof": "<strong>Why it wins:</strong> strong battery confidence, easy cleaning, useful attachments, and the safest mainstream ownership profile for regular beard maintenance."
  },
  {
    "title": "Electric Shaver",
    "slug": "electric-shaver",
    "url": "/electric-shaver.html",
    "group": "Personal Care",
    "cardTitle": "The electric shaver that makes the most sense",
    "decision": "Braun Series 9 Pro+",
    "image": "/Braun-Series9.png",
    "imageAlt": "Braun Series 9 Pro+ electric shaver",
    "summary": "The best electric shaver for most men: a safer premium balance of comfort, closeness, reliability, and long-term ownership than more aggressive or more niche alternatives.",
    "proof": "balances daily comfort, close-enough performance, broad parts support, and low-regret ownership better than the main foil and rotary alternatives.",
    "price": "Typical price: $250–$450",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $250–$450",
    "featuredQuote": "“The best electric shaver for most men: Braun Series 9 Pro+ — comfortable, close enough, reliable, and easier to defend than aggressive or niche alternatives.”",
    "featuredProof": "<strong>Why it wins:</strong> strong comfort, broad availability, mature replacement support, and the safest low-regret ownership profile for daily face shaving."
  },
  {
    "title": "Massage Gun",
    "slug": "massage-gun",
    "url": "/massage-gun.html",
    "group": "Personal Care",
    "cardTitle": "The massage gun that makes the most sense",
    "decision": "Ekrin B37v2",
    "image": "/Ekrin-Athletics-B37v2.png",
    "imageAlt": "Ekrin B37v2 massage gun",
    "summary": "The best massage gun for most people: strong enough for real recovery, comfortable enough to keep using, and a more defensible ownership fit than louder, heavier, or cheaper alternatives.",
    "proof": "balances reliability, power, quiet use, comfort, and value better than premium overkill or no-name budget models.",
    "price": "Typical price: $250–$330",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $250–$330",
    "featuredQuote": "“The best massage gun for most people: Ekrin B37v2 — strong, comfortable, quiet enough, and easier to defend than premium overkill or cheap clones.”",
    "featuredProof": "<strong>Why it wins:</strong> the strongest mainstream balance of reliability signal, real recovery performance, comfortable handling, quiet use, and long-term value."
  },
  {
    "title": "Electric Toothbrush",
    "slug": "electric-toothbrush",
    "url": "/electric-toothbrush.html",
    "group": "Personal Care",
    "cardTitle": "The electric toothbrush most people should stop at",
    "decision": "Philips Sonicare 4100 Series",
    "image": "/PHILIPS_SONICARE_4100__transparent_.png",
    "imageAlt": "Philips Sonicare 4100 Series",
    "summary": "The best electric toothbrush for most people: reliable daily cleaning without the app extras, charger clutter, or premium price creep that rarely improves outcomes.",
    "proof": "proven daily cleaning with pressure sensing and fewer gimmicks than pricier models.",
    "price": "Typical price: $50–$90",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $50–$90",
    "featuredQuote": "“The best electric toothbrush for most people: Philips Sonicare 4100 Series — reliable daily cleaning, simple ownership, and fewer premium extras.”",
    "featuredProof": "<strong>Why it wins:</strong> proven daily cleaning with pressure sensing and fewer gimmicks than pricier models."
  },
  {
    "title": "Hair Dryer",
    "slug": "hair-dryer",
    "url": "/hair-dryer.html",
    "group": "Personal Care",
    "cardTitle": "The hair dryer that makes the most sense",
    "decision": "T3 AireLuxe Hair Dryer",
    "image": "/t3-aireluxe.png",
    "imageAlt": "T3 AireLuxe Hair Dryer",
    "summary": "The best hair dryer for most people: controlled drying, easier daily use, and a stronger ownership case than cheap dryers or luxury systems.",
    "proof": "balanced reliability, comfort, control, and value make it more defensible than cheap dryers and less excessive than Dyson-level pricing.",
    "price": "Typical price: $180–$250",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $180–$250",
    "featuredQuote": "“The best hair dryer for most people: T3 AireLuxe Hair Dryer — controlled drying, daily comfort, and practical premium ownership without Dyson-level pricing.”",
    "featuredProof": "<strong>Why it wins:</strong> balanced reliability, comfort, control, and value make it more defensible than cheap dryers and less excessive than luxury systems."
  },
  {
    "title": "Hair Straightener",
    "slug": "hair-straightener",
    "url": "/hair-straightener.html",
    "group": "Personal Care",
    "cardTitle": "The hair straightener that makes the most sense",
    "decision": "BaBylissPRO Nano Titanium Ultra-Thin 1”",
    "image": "/BaBylissPRO-Nano-Titanium-Ultra-Thin.png",
    "imageAlt": "BaBylissPRO Nano Titanium Ultra-Thin 1 inch",
    "summary": "The best hair straightener for most people: fast styling, smooth titanium plates, broad everyday usability, and a stronger ownership case than cheaper tools.",
    "proof": "fast styling, smooth titanium plates, and strong ownership credibility make it more defensible than cheap flat irons and less excessive than luxury tools.",
    "price": "Typical price: $140–$180",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $140–$180",
    "featuredQuote": "“The best hair straightener for most people: BaBylissPRO Nano Titanium Ultra-Thin 1” — fast styling, smooth titanium plates, and practical everyday ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> fast styling, smooth titanium plates, and strong ownership credibility make it more defensible than cheap flat irons and less excessive than luxury tools."
  },
  {
    "title": "Curling Iron",
    "slug": "curling-iron",
    "url": "/curling-iron.html",
    "group": "Personal Care",
    "cardTitle": "The curling iron that makes the most sense",
    "decision": "T3 SinglePass Curl X, 1.25”",
    "image": "/T3-SinglePass-CurlX.png",
    "imageAlt": "T3 SinglePass Curl X 1.25 inch curling iron",
    "summary": "The best curling iron for most people: controlled heat, smooth styling, long-barrel usability, and fewer regrets than cheap, overly hot, or overcomplicated alternatives.",
    "proof": "balances curl performance, heat control, everyday usability, and long-term ownership better than budget irons, automatic curlers, or premium air-styling systems.",
    "price": "Typical price: $130–$230",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $130–$230",
    "featuredQuote": "“The best curling iron for most people: T3 SinglePass Curl X, 1.25” — controlled heat, smooth styling, and practical premium ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> controlled heat, long-barrel usability, smooth handling, and a safer broad-use decision than cheap irons or overcomplicated styling systems."
  },

  {
    "title": "E-Reader",
    "slug": "e-reader",
    "url": "/e-reader.html",
    "group": "Tech",
    "cardTitle": "The e-reader that makes the most sense",
    "decision": "Kobo Clara BW",
    "image": "/Kobo-Clara-BW.png",
    "imageAlt": "Kobo Clara BW",
    "summary": "The best e-reader for most people: strong black-and-white reading, library-friendly ownership, and fewer ecosystem regrets than cheaper, colour-first, or country-limited alternatives.",
    "proof": "avoids the biggest e-reader mistake: buying into the wrong ecosystem for your country, library habits, and everyday reading.",
    "price": "Typical price: $140–$160",
    "featured": true,
    "featuredSub": "Tech · Typical price: $140–$160",
    "featuredQuote": "“The best e-reader for most people: Kobo Clara BW — simple, library-friendly, and safer for long-term ownership across Canada and the U.S.”",
    "featuredProof": "<strong>Why it wins:</strong> sharp black-and-white reading, warm light, waterproofing, no lock-screen ads, broad file support, and a safer cross-border library fit."
  }
];
