module.exports = [
  {
    "title": "Blender",
    "slug": "blender",
    "url": "/blender.html",
    "group": "Kitchen",
    "cardTitle": "The blender that makes the most sense",
    "decision": "Vitamix 5200",
    "image": "/Vitamix_5200.png",
    "imageAlt": "Vitamix 5200",
    "summary": "The best blender for most people: proven long-term durability, consistent blending across hard use cases, and a simple design with fewer failure points.",
    "proof": "avoids the replacement cycle better than cheaper and more feature-heavy blenders.",
    "price": "Typical price: $350–$480",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $350–$480",
    "featuredQuote": "“The best blender for most people: Vitamix 5200: proven durability, consistent performance, and simple long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> proven motor durability, consistent results across smoothies, frozen fruit, nut butters, and soups, and a simple low-failure design."
  },
  {
    "title": "Air Fryer",
    "slug": "air-fryer",
    "url": "/air-fryer.html",
    "group": "Kitchen",
    "cardTitle": "The air fryer most kitchens should buy",
    "decision": "Instant Vortex Plus 6-Quart",
    "image": "/Instant_Vortex_Plus__transparent_.png",
    "imageAlt": "Instant Vortex Plus",
    "summary": "The best air fryer for most people: enough capacity for real meals, strong everyday performance, and fewer tradeoffs than oversized or ultra-cheap options.",
    "proof": "the 6-quart size hits the sweet spot for daily cooking without overbuying capacity or features.",
    "price": "Typical price: $100–$200",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $100–$200",
    "featuredQuote": "“The best air fryer for most people: Instant Vortex Plus 6-Quart: practical capacity, strong everyday cooking, and simpler long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> the 6-quart size hits the sweet spot for daily meals without paying for features most households ignore."
  },
  {
    "title": "Coffee Grinder",
    "slug": "coffee-grinder",
    "url": "/coffee-grinder.html",
    "group": "Kitchen",
    "cardTitle": "The coffee grinder that makes the most sense",
    "decision": "Baratza Encore ESP",
    "image": "/baratza-encore-esp.png",
    "imageAlt": "Baratza Encore ESP",
    "summary": "The best coffee grinder for most people: consistent burr grinding across brew styles, strong long-term usability, and a simpler ownership fit than specialized grinders.",
    "proof": "reliable grind quality and broad brew coverage without stepping into specialist complexity.",
    "price": "Typical price: $180–$220",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $180–$220",
    "featuredQuote": "“The best coffee grinder for most people: Baratza Encore ESP: consistent burr grinding, broad brew coverage, and a simpler long-term fit.”",
    "featuredProof": "<strong>Why it wins:</strong> dependable grind quality, strong owner trust, and a broader use case than more specialized grinders."
  },

  {
    "title": "Espresso Machine",
    "slug": "espresso-machine",
    "url": "/espresso-machine.html",
    "group": "Kitchen",
    "cardTitle": "The espresso machine that makes the most sense",
    "decision": "Breville Bambino Plus",
    "image": "/Bambino_Plus.png",
    "imageAlt": "Breville Bambino Plus espresso machine",
    "summary": "The best espresso machine for most people: real espresso and milk drinks, fast daily use, compact size, and fewer long-term compromises than all-in-one grinder machines.",
    "proof": "strong daily usability, a forgiving milk workflow, and no built-in grinder dependency make it the cleanest mainstream decision.",
    "price": "Typical price: $400–$500",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $400–$500",
    "featuredQuote": "“The best espresso machine for most people: Breville Bambino Plus: real espresso, easy milk drinks, compact ownership, and fewer long-term compromises.”",
    "featuredProof": "<strong>Why it wins:</strong> strong daily usability, automatic milk support, compact size, and no built-in grinder dependency."
  },

  {
    "title": "Toaster Oven",
    "slug": "toaster-oven",
    "url": "/toaster-oven.html",
    "group": "Kitchen",
    "cardTitle": "The toaster oven that makes the most sense",
    "decision": "Breville Smart Oven Pro",
    "image": "/Breville-Smart-Oven-Pro.png",
    "imageAlt": "Breville Smart Oven Pro toaster oven",
    "summary": "The best toaster oven for most people: reliable everyday cooking, useful capacity, clear controls, and fewer regrets than cheap or oversized alternatives.",
    "proof": "balances toast, reheating, baking, and small meals without forcing most buyers into a giant air-fryer oven.",
    "price": "Typical price: $250–$350",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $250–$350",
    "featuredQuote": "“The best toaster oven for most people: Breville Smart Oven Pro: practical capacity, predictable cooking, and daily usability without oversized-appliance regret.”",
    "featuredProof": "<strong>Why it wins:</strong> the strongest mainstream balance of cooking consistency, capacity, controls, and long-term ownership confidence."
  },
  {
    "title": "Instant Pot",
    "slug": "instant-pot",
    "url": "/instant-pot.html",
    "group": "Kitchen",
    "cardTitle": "The Instant Pot that makes the most sense",
    "decision": "Instant Pot Duo Plus 6 qt",
    "image": "/Instant-Pot-Duo-Plus-6-qrt.png",
    "imageAlt": "Instant Pot Duo Plus 6 qt",
    "summary": "The best Instant Pot for most people: the proven 6-quart format, easier daily usability than the basic Duo, and fewer regrets than smart, oversized, or air-fryer models.",
    "proof": "keeps the classic Instant Pot benefit while avoiding the cost, bulk, and complexity most buyers do not need.",
    "price": "Typical price: $110–$160",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $110–$160",
    "featuredQuote": "“The best Instant Pot for most people: Instant Pot Duo Plus 6 qt: proven 6-quart usability, a cleaner daily experience, and no premium-model clutter.”",
    "featuredProof": "<strong>Why it wins:</strong> it keeps the dependable Instant Pot formula, improves the daily interface, and avoids the size, cost, and complexity of air-fryer or smart models."
  },

  {
    "title": "Rice Cooker",
    "slug": "rice-cooker",
    "url": "/rice-cooker.html",
    "group": "Kitchen",
    "cardTitle": "The rice cooker that makes the most sense",
    "decision": "Zojirushi NS-ZCC10 Neuro Fuzzy",
    "image": "/Zojirushi-Overall-Best.png",
    "imageAlt": "Zojirushi NS-ZCC10 Neuro Fuzzy rice cooker",
    "summary": "The best rice cooker for most people: proven long-term reliability, forgiving rice consistency, and fewer regrets than cheap basic cookers or premium overkill.",
    "proof": "balances rice quality, keep-warm performance, usability, and long-term ownership better than cheaper or more complex alternatives.",
    "price": "Typical price: $230–$320",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $230–$320",
    "featuredQuote": "“The best rice cooker for most people: Zojirushi NS-ZCC10 Neuro Fuzzy: reliable, forgiving, and easier to defend than cheap cookers or premium overkill.”",
    "featuredProof": "<strong>Why it wins:</strong> the strongest ownership pattern, forgiving fuzzy logic, practical 5.5-cup capacity, and fewer long-term regrets than cheaper or more complex models."
  },

  {
    "title": "Food Processor",
    "slug": "food-processor",
    "url": "/food-processor.html",
    "group": "Kitchen",
    "cardTitle": "The food processor that makes the most sense",
    "decision": "Cuisinart Custom 14-Cup",
    "image": "/Cuisinart-Custom-14Cup.png",
    "imageAlt": "Cuisinart Custom 14-Cup Food Processor",
    "summary": "The best food processor for most people: proven full-size reliability, practical 14-cup capacity, and simpler ownership than cheap or feature-heavy alternatives.",
    "proof": "handles the core prep jobs most people actually repeat without forcing buyers into accessory clutter or premium overkill.",
    "price": "Typical price: $200–$320",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $200–$320",
    "featuredQuote": "“The best food processor for most people: Cuisinart Custom 14-Cup: proven, practical, and easier to defend than cheap or overbuilt alternatives.”",
    "featuredProof": "<strong>Why it wins:</strong> long-term owner trust, useful 14-cup capacity, simple controls, and fewer regret points than mini, budget, or attachment-heavy machines."
  },

  {
    "title": "Nonstick Pan",
    "slug": "nonstick-pan",
    "url": "/nonstick-pan.html",
    "group": "Kitchen",
    "cardTitle": "The nonstick pan that makes the most sense",
    "decision": "Tramontina Professional Fusion 10-Inch",
    "image": "/Tramontina_Professional.png",
    "imageAlt": "Tramontina Professional Fusion 10-Inch Nonstick Fry Pan",
    "summary": "The best nonstick pan for most people: reliable everyday release, easy cleanup, and a realistic replacement cost for cookware that eventually wears out.",
    "proof": "treats nonstick like a wear item instead of forcing buyers into premium overpayment.",
    "price": "Typical price: $25–$45",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $25–$45",
    "featuredQuote": "“The best nonstick pan for most people: Tramontina Professional Fusion 10-Inch: simple, reliable, easy to clean, and priced for real ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> strong everyday nonstick performance, a rivetless interior that is easier to clean, and a price that makes replacement rational when the coating eventually declines."
  },

  {
    "title": "Electric Kettle",
    "slug": "electric-kettle",
    "url": "/electric-kettle.html",
    "group": "Kitchen",
    "cardTitle": "The electric kettle that makes the most sense",
    "decision": "Cuisinart PerfecTemp Electric Kettle",
    "image": "/Cuisinart-PerfectTemp.png",
    "imageAlt": "Cuisinart PerfecTemp electric kettle",
    "summary": "The best electric kettle for most people: useful temperature presets, proven everyday usability, broad North American availability, and fewer regrets than niche or design-first alternatives.",
    "proof": "balances reliability, tea-friendly controls, simple daily use, and realistic availability better than prettier or more specialized kettles.",
    "price": "Typical price: $80–$130",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $80–$130",
    "featuredQuote": "“The best electric kettle for most people: Cuisinart PerfecTemp Electric Kettle: reliable presets, broad availability, and simple daily ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> useful temperature presets, a long ownership track record, simple daily controls, and a cleaner North America-wide buying path."
  },
  {
    "title": "Robot Vacuum",
    "slug": "robot-vacuum",
    "url": "/robot-vacuum.html",
    "group": "Home Essentials",
    "cardTitle": "The robot vacuum that best balances automation and reliability",
    "decision": "Roborock Qrevo Curv",
    "image": "/ROBOROCK_QREVO_TRANSPARENT_FOR_NOTION.png",
    "imageAlt": "Roborock Qrevo Curv",
    "summary": "The best robot vacuum for most people: high-end convenience that still feels rational, with strong navigation, solid dock automation, and fewer painful compromises.",
    "proof": "strong daily automation without stepping into the most failure-prone premium complexity.",
    "price": "Typical price: $850–$1,200",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $850–$1,200",
    "featuredQuote": "“The best robot vacuum for most people: Roborock Qrevo Curv: strong automation, reliable navigation, and a dock that feels worth the money.”",
    "featuredProof": "<strong>Why it wins:</strong> strong daily automation without stepping into the most failure-prone premium complexity."
  },
  {
    "title": "Air Purifier",
    "slug": "air-purifier",
    "url": "/air-purifier.html",
    "group": "Home Essentials",
    "cardTitle": "The air purifier that makes the most sense",
    "decision": "Coway AP-1512HH Mighty",
    "image": "/coway-air-purifier.png",
    "imageAlt": "Coway AP-1512HH Mighty",
    "summary": "The best air purifier for most people: real airflow for everyday rooms, reasonable filter costs, and fewer long-term tradeoffs than feature-heavy alternatives.",
    "proof": "balanced airflow, realistic room coverage, and filter costs that stay manageable over time.",
    "price": "Typical price: $180–$250",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $180–$250",
    "featuredQuote": "“The best air purifier for most people: Coway AP-1512HH Mighty: real airflow, manageable filter costs, and dependable everyday ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> balanced airflow, realistic room coverage, and filter costs that stay manageable over time."
  },
  {
    "title": "Video Doorbell",
    "slug": "video-doorbell",
    "url": "/video-doorbell.html",
    "group": "Home Essentials",
    "cardTitle": "The video doorbell that makes the most sense",
    "decision": "Ring Battery Doorbell Plus",
    "image": "/ring_battery_doorbell_plus.png",
    "imageAlt": "Ring Battery Doorbell Plus",
    "summary": "The best video doorbell for most people: easy installation, reliable alerts, strong app experience, and a removable battery that makes ownership less annoying.",
    "proof": "solves the mainstream ownership problem better than cheaper or more technical alternatives.",
    "price": "Typical price: $150–$250",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $150–$250",
    "featuredQuote": "“The best video doorbell for most people: Ring Battery Doorbell Plus: easy setup, reliable alerts, and less annoying long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> strong mainstream reliability, a removable battery, good package visibility, and a mature app ecosystem."
  },

  {
    "title": "Cordless Vacuum",
    "slug": "cordless-vacuum",
    "url": "/cordless-vacuum.html",
    "group": "Home Essentials",
    "cardTitle": "The cordless vacuum that makes the most sense",
    "decision": "Dyson V15 Detect",
    "image": "/Dyson-V15.png",
    "imageAlt": "Dyson V15 Detect cordless vacuum",
    "summary": "The best cordless vacuum for most people: strong mixed-floor cleaning, proven pet-hair performance, and a mature ownership case without paying for newer flagship complexity.",
    "proof": "balances cleaning power, pet-hair handling, usability, and long-term confidence better than cheaper or newer alternatives.",
    "price": "Typical price: $550–$750",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $550–$750",
    "featuredQuote": "“The best cordless vacuum for most people: Dyson V15 Detect: strong mixed-floor cleaning, pet-hair confidence, and proven ownership without flagship overkill.”",
    "featuredProof": "<strong>Why it wins:</strong> broad cleaning performance, strong pet-hair pickup, mature accessory support, and fewer unknowns than newer dock-based or flagship models."
  },
  {
    "title": "Upright Vacuum",
    "slug": "upright-vacuum",
    "url": "/upright-vacuum.html",
    "group": "Home Essentials",
    "cardTitle": "The upright vacuum that makes the most sense",
    "decision": "Shark Stratos Upright Vacuum",
    "image": "/Shark-Stratos-Upright.png",
    "imageAlt": "Shark Stratos Upright Vacuum",
    "summary": "The best upright vacuum for most people: stronger carpet cleaning, pet-hair confidence, and whole-home usability without specialty-vacuum pricing.",
    "proof": "balances carpet performance, hair control, sealed filtration, and practical ownership better than heavier or cheaper alternatives.",
    "price": "Typical price: $300–$550",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $300–$550",
    "featuredQuote": "“The best upright vacuum for most people: Shark Stratos Upright Vacuum: serious carpet cleaning, pet-hair confidence, and practical whole-home ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> strong mainstream cleaning, better hair handling, lift-away versatility, and a more defensible ownership fit than heavier or cheaper alternatives."
  },

  {
    "title": "Dehumidifier",
    "slug": "dehumidifier",
    "url": "/dehumidifier.html",
    "group": "Home Essentials",
    "cardTitle": "The dehumidifier that makes the most sense",
    "decision": "Midea Cube 50 Pint",
    "image": "/Midea-Cute-50-Pint.png",
    "imageAlt": "Midea Cube 50 Pint dehumidifier",
    "summary": "The best dehumidifier for most people: serious moisture removal, a large tank, simple drainage, and fewer long-term regrets than tiny units or pump-first alternatives.",
    "proof": "handles real household humidity without forcing most buyers into pump complexity or commercial pricing.",
    "price": "Typical price: $230–$330",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $230–$330",
    "featuredQuote": "“The best dehumidifier for most people: Midea Cube 50 Pint: serious moisture removal, easier daily ownership, and no unnecessary pump complexity.”",
    "featuredProof": "<strong>Why it wins:</strong> strong moisture removal, a large tank, continuous drainage, and a simpler reliability profile than pump-heavy or underpowered alternatives."
  },

  {
    "title": "Humidifier",
    "slug": "humidifier",
    "url": "/humidifier.html",
    "group": "Home Essentials",
    "cardTitle": "The humidifier that makes the most sense",
    "decision": "Levoit Classic 300S",
    "image": "/Levoit-Classic-300S.png",
    "imageAlt": "Levoit Classic 300S humidifier",
    "summary": "The best humidifier for most people: quiet bedroom-friendly use, easy top-fill ownership, realistic tank capacity, and fewer regrets than tiny budget units or oversized large-room machines.",
    "proof": "balances daily comfort, refill convenience, cleaning burden, and availability better than mist-heavy or feature-first alternatives.",
    "price": "Typical price: $80–$130",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $80–$130",
    "featuredQuote": "“The best humidifier for most people: Levoit Classic 300S: quiet, easy to refill, and sized for normal rooms without overbuying.”",
    "featuredProof": "<strong>Why it wins:</strong> the strongest mainstream balance of quiet use, top-fill convenience, realistic capacity, and long-term ownership simplicity."
  },


  {
    "title": "Water Flosser",
    "slug": "water-flosser",
    "url": "/water-flosser.html",
    "group": "Personal Care",
    "cardTitle": "The water flosser that makes the most sense",
    "decision": "Waterpik Aquarius Water Flosser",
    "image": "/Waterpik-Aquarius.png",
    "imageAlt": "Waterpik Aquarius Water Flosser",
    "summary": "The best water flosser for most people: reliable daily cleaning, a full-size tank, easy tip replacement, and fewer compromises than cordless or cheap high-spec alternatives.",
    "proof": "solves the real ownership problem: enough tank capacity, pressure control, and a proven tip ecosystem without battery or tiny-reservoir friction.",
    "price": "Typical price: $70–$110",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $70–$110",
    "featuredQuote": "“The best water flosser for most people: Waterpik Aquarius Water Flosser: reliable daily cleaning, a full-size tank, and fewer compromises than cordless alternatives.”",
    "featuredProof": "<strong>Why it wins:</strong> proven Waterpik ownership patterns, practical tank size, broad tip support, and a simpler long-term reliability case than battery-powered or cheap clone models."
  },

  {
    "title": "Beard Trimmer",
    "slug": "beard-trimmer",
    "url": "/beard-trimmer.html",
    "group": "Personal Care",
    "cardTitle": "The beard trimmer that makes the most sense",
    "decision": "Philips Norelco Multigroom 9000",
    "image": "/Philips-Norelco-Multigroom-9000.png",
    "imageAlt": "Philips Norelco Multigroom 9000",
    "summary": "The best beard trimmer for most people: dependable trimming, strong battery life, useful attachments, and easier long-term ownership than cheap kits or barber-style tools.",
    "proof": "solves the real ownership problem: clean repeatable beard maintenance without weak batteries, flimsy guards, or attachment clutter.",
    "price": "Typical price: $80–$130",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $80–$130",
    "featuredQuote": "“The best beard trimmer for most people: Philips Norelco Multigroom 9000: reliable, versatile, and easier to live with than cheap kits or pro-style tools.”",
    "featuredProof": "<strong>Why it wins:</strong> strong battery confidence, easy cleaning, useful attachments, and the safest mainstream ownership profile for regular beard maintenance."
  },
  {
    "title": "Electric Shaver",
    "slug": "electric-shaver",
    "url": "/electric-shaver.html",
    "group": "Personal Care",
    "cardTitle": "The electric shaver that makes the most sense",
    "decision": "Braun Series 9 Pro+",
    "image": "/Braun-Series9.png",
    "imageAlt": "Braun Series 9 Pro+ electric shaver",
    "summary": "The best electric shaver for most men: a safer premium balance of comfort, closeness, reliability, and long-term ownership than more aggressive or more niche alternatives.",
    "proof": "balances daily comfort, close-enough performance, broad parts support, and low-regret ownership better than the main foil and rotary alternatives.",
    "price": "Typical price: $250–$450",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $250–$450",
    "featuredQuote": "“The best electric shaver for most men: Braun Series 9 Pro+: comfortable, close enough, reliable, and easier to defend than aggressive or niche alternatives.”",
    "featuredProof": "<strong>Why it wins:</strong> strong comfort, broad availability, mature replacement support, and the safest low-regret ownership profile for daily face shaving."
  },
  {
    "title": "Massage Gun",
    "slug": "massage-gun",
    "url": "/massage-gun.html",
    "group": "Personal Care",
    "cardTitle": "The massage gun that makes the most sense",
    "decision": "Ekrin B37v2",
    "image": "/Ekrin-Athletics-B37v2.png",
    "imageAlt": "Ekrin B37v2 massage gun",
    "summary": "The best massage gun for most people: strong enough for real recovery, comfortable enough to keep using, and a more defensible ownership fit than louder, heavier, or cheaper alternatives.",
    "proof": "balances reliability, power, quiet use, comfort, and value better than premium overkill or no-name budget models.",
    "price": "Typical price: $250–$330",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $250–$330",
    "featuredQuote": "“The best massage gun for most people: Ekrin B37v2: strong, comfortable, quiet enough, and easier to defend than premium overkill or cheap clones.”",
    "featuredProof": "<strong>Why it wins:</strong> the strongest mainstream balance of reliability signal, real recovery performance, comfortable handling, quiet use, and long-term value."
  },
  {
    "title": "Electric Toothbrush",
    "slug": "electric-toothbrush",
    "url": "/electric-toothbrush.html",
    "group": "Personal Care",
    "cardTitle": "The electric toothbrush most people should stop at",
    "decision": "Philips Sonicare 4100 Series",
    "image": "/PHILIPS_SONICARE_4100__transparent_.png",
    "imageAlt": "Philips Sonicare 4100",
    "summary": "The best electric toothbrush for most people: reliable daily cleaning without the app extras, charger clutter, or premium price creep that rarely improves outcomes.",
    "proof": "proven daily cleaning with pressure sensing and fewer gimmicks than pricier models.",
    "price": "Typical price: $50–$90",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $50–$90",
    "featuredQuote": "“The best electric toothbrush for most people: Philips Sonicare 4100 Series: reliable daily cleaning, simple ownership, and fewer premium extras.”",
    "featuredProof": "<strong>Why it wins:</strong> proven daily cleaning with pressure sensing and fewer gimmicks than pricier models."
  },
  {
    "title": "Hair Dryer",
    "slug": "hair-dryer",
    "url": "/hair-dryer.html",
    "group": "Personal Care",
    "cardTitle": "The hair dryer that makes the most sense",
    "decision": "T3 AireLuxe",
    "image": "/t3-aireluxe.png",
    "imageAlt": "T3 AireLuxe",
    "summary": "The best hair dryer for most people: controlled drying, easier daily use, and a stronger ownership case than cheap dryers or luxury systems.",
    "proof": "balanced reliability, comfort, control, and value make it more defensible than cheap dryers and less excessive than Dyson-level pricing.",
    "price": "Typical price: $180–$250",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $180–$250",
    "featuredQuote": "“The best hair dryer for most people: T3 AireLuxe: controlled drying, daily comfort, and practical premium ownership without Dyson-level pricing.”",
    "featuredProof": "<strong>Why it wins:</strong> balanced reliability, comfort, control, and value make it more defensible than cheap dryers and less excessive than luxury systems."
  },
  {
    "title": "Hair Straightener",
    "slug": "hair-straightener",
    "url": "/hair-straightener.html",
    "group": "Personal Care",
    "cardTitle": "The hair straightener that makes the most sense",
    "decision": "T3 SinglePass StyleMax 1”",
    "image": "/T3-SinglePass-StyleMax-Professional-1.webp",
    "imageAlt": "T3 SinglePass StyleMax 1 inch",
    "summary": "The best hair straightener for most people: controlled heat, smooth styling, broad everyday usability, and a stronger ownership case than cheaper tools.",
    "proof": "balanced reliability, controlled heat, and ease of use make it more defensible than cheap flat irons and less excessive than luxury tools.",
    "price": "Typical price: $180–$250",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $180–$250",
    "featuredQuote": "“The best hair straightener for most people: T3 SinglePass StyleMax 1”: controlled heat, smooth styling, and practical everyday ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> balanced reliability, controlled heat, and ease of use make it more defensible than cheap flat irons and less excessive than luxury tools."
  },
  {
    "title": "Curling Iron",
    "slug": "curling-iron",
    "url": "/curling-iron.html",
    "group": "Personal Care",
    "cardTitle": "The curling iron that makes the most sense",
    "decision": "T3 SinglePass Curl X, 1.25”",
    "image": "/T3-SinglePass-CurlX.png",
    "imageAlt": "T3 SinglePass Curl X 1.25 inch curling iron",
    "summary": "The best curling iron for most people: controlled heat, smooth styling, long-barrel usability, and fewer regrets than cheap, overly hot, or overcomplicated alternatives.",
    "proof": "balances curl performance, heat control, everyday usability, and long-term ownership better than budget irons, automatic curlers, or premium air-styling systems.",
    "price": "Typical price: $130–$230",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $130–$230",
    "featuredQuote": "“The best curling iron for most people: T3 SinglePass Curl X, 1.25”: controlled heat, smooth styling, and practical premium ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> controlled heat, long-barrel usability, smooth handling, and a safer broad-use decision than cheap irons or overcomplicated styling systems."
  }
];
