module.exports = [
  {
    "title": "Blender",
    "slug": "blender",
    "url": "/blender.html",
    "group": "Kitchen",
    "cardTitle": "The blender that makes the most sense",
    "decision": "Vitamix 5200",
    "image": "/Vitamix_5200.png",
    "imageAlt": "Vitamix 5200",
    "summary": "The best blender for most people: proven long-term durability, consistent blending across hard use cases, and a simple design with fewer failure points.",
    "proof": "avoids the replacement cycle better than cheaper and more feature-heavy blenders.",
    "price": "Typical price: $350–$480",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $350–$480",
    "featuredQuote": "“The best blender for most people: Vitamix 5200 — proven durability, consistent performance, and simple long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> proven motor durability, consistent results across smoothies, frozen fruit, nut butters, and soups, and a simple low-failure design."
  },
  {
    "title": "Air Fryer",
    "slug": "air-fryer",
    "url": "/air-fryer.html",
    "group": "Kitchen",
    "cardTitle": "The air fryer most kitchens should buy",
    "decision": "Instant Vortex Plus 6-Quart",
    "image": "/Instant_Vortex_Plus__transparent_.png",
    "imageAlt": "Instant Vortex Plus",
    "summary": "The best air fryer for most people: enough capacity for real meals, strong everyday performance, and fewer tradeoffs than oversized or ultra-cheap options.",
    "proof": "the 6-quart size hits the sweet spot for daily cooking without overbuying capacity or features.",
    "price": "Typical price: $100–$200",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $100–$200",
    "featuredQuote": "“The best air fryer for most people: Instant Vortex Plus 6-Quart — practical capacity, strong everyday cooking, and simpler long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> the 6-quart size hits the sweet spot for daily meals without paying for features most households ignore."
  },
  {
    "title": "Coffee Grinder",
    "slug": "coffee-grinder",
    "url": "/coffee-grinder.html",
    "group": "Kitchen",
    "cardTitle": "The coffee grinder that makes the most sense",
    "decision": "Baratza Encore ESP",
    "image": "/baratza-encore-esp.png",
    "imageAlt": "Baratza Encore ESP",
    "summary": "The best coffee grinder for most people: consistent burr grinding across brew styles, strong long-term usability, and a simpler ownership fit than specialized grinders.",
    "proof": "reliable grind quality and broad brew coverage without stepping into specialist complexity.",
    "price": "Typical price: $180–$220",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $180–$220",
    "featuredQuote": "“The best coffee grinder for most people: Baratza Encore ESP — consistent burr grinding, broad brew coverage, and a simpler long-term fit.”",
    "featuredProof": "<strong>Why it wins:</strong> dependable grind quality, strong owner trust, and a broader use case than more specialized grinders."
  },

  {
    "title": "Espresso Machine",
    "slug": "espresso-machine",
    "url": "/espresso-machine.html",
    "group": "Kitchen",
    "cardTitle": "The espresso machine that makes the most sense",
    "decision": "Breville Bambino Plus",
    "image": "/Bambino_Plus.png",
    "imageAlt": "Breville Bambino Plus espresso machine",
    "summary": "The best espresso machine for most people: real espresso and milk drinks, fast daily use, compact size, and fewer long-term compromises than all-in-one grinder machines.",
    "proof": "strong daily usability, a forgiving milk workflow, and no built-in grinder dependency make it the cleanest mainstream decision.",
    "price": "Typical price: $400–$500",
    "featured": true,
    "featuredSub": "Kitchen · Typical price: $400–$500",
    "featuredQuote": "“The best espresso machine for most people: Breville Bambino Plus — real espresso, easy milk drinks, compact ownership, and fewer long-term compromises.”",
    "featuredProof": "<strong>Why it wins:</strong> strong daily usability, automatic milk support, compact size, and no built-in grinder dependency."
  },
  {
    "title": "Robot Vacuum",
    "slug": "robot-vacuum",
    "url": "/robot-vacuum.html",
    "group": "Home Essentials",
    "cardTitle": "The robot vacuum that best balances automation and reliability",
    "decision": "Roborock Qrevo Curv",
    "image": "/ROBOROCK_QREVO_TRANSPARENT_FOR_NOTION.png",
    "imageAlt": "Roborock Qrevo Curv",
    "summary": "The best robot vacuum for most people: high-end convenience that still feels rational, with strong navigation, solid dock automation, and fewer painful compromises.",
    "proof": "strong daily automation without stepping into the most failure-prone premium complexity.",
    "price": "Typical price: $850–$1,200",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $850–$1,200",
    "featuredQuote": "“The best robot vacuum for most people: Roborock Qrevo Curv — strong automation, reliable navigation, and a dock that feels worth the money.”",
    "featuredProof": "<strong>Why it wins:</strong> strong daily automation without stepping into the most failure-prone premium complexity."
  },
  {
    "title": "Air Purifier",
    "slug": "air-purifier",
    "url": "/air-purifier.html",
    "group": "Home Essentials",
    "cardTitle": "The air purifier that makes the most sense",
    "decision": "Coway AP-1512HH Mighty",
    "image": "/coway-air-purifier.png",
    "imageAlt": "Coway AP-1512HH Mighty",
    "summary": "The best air purifier for most people: real airflow for everyday rooms, reasonable filter costs, and fewer long-term tradeoffs than feature-heavy alternatives.",
    "proof": "balanced airflow, realistic room coverage, and filter costs that stay manageable over time.",
    "price": "Typical price: $180–$250",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $180–$250",
    "featuredQuote": "“The best air purifier for most people: Coway AP-1512HH Mighty — real airflow, manageable filter costs, and dependable everyday ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> balanced airflow, realistic room coverage, and filter costs that stay manageable over time."
  },
  {
    "title": "Video Doorbell",
    "slug": "video-doorbell",
    "url": "/video-doorbell.html",
    "group": "Home Essentials",
    "cardTitle": "The video doorbell that makes the most sense",
    "decision": "Ring Battery Doorbell Plus",
    "image": "/ring_battery_doorbell_plus.png",
    "imageAlt": "Ring Battery Doorbell Plus",
    "summary": "The best video doorbell for most people: easy installation, reliable alerts, strong app experience, and a removable battery that makes ownership less annoying.",
    "proof": "solves the mainstream ownership problem better than cheaper or more technical alternatives.",
    "price": "Typical price: $150–$250",
    "featured": true,
    "featuredSub": "Home Essentials · Typical price: $150–$250",
    "featuredQuote": "“The best video doorbell for most people: Ring Battery Doorbell Plus — easy setup, reliable alerts, and less annoying long-term ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> strong mainstream reliability, a removable battery, good package visibility, and a mature app ecosystem."
  },
  {
    "title": "Electric Toothbrush",
    "slug": "electric-toothbrush",
    "url": "/electric-toothbrush.html",
    "group": "Personal Care",
    "cardTitle": "The electric toothbrush most people should stop at",
    "decision": "Philips Sonicare 4100 Series",
    "image": "/PHILIPS_SONICARE_4100__transparent_.png",
    "imageAlt": "Philips Sonicare 4100",
    "summary": "The best electric toothbrush for most people: reliable daily cleaning without the app extras, charger clutter, or premium price creep that rarely improves outcomes.",
    "proof": "proven daily cleaning with pressure sensing and fewer gimmicks than pricier models.",
    "price": "Typical price: $50–$90",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $50–$90",
    "featuredQuote": "“The best electric toothbrush for most people: Philips Sonicare 4100 Series — reliable daily cleaning, simple ownership, and fewer premium extras.”",
    "featuredProof": "<strong>Why it wins:</strong> proven daily cleaning with pressure sensing and fewer gimmicks than pricier models."
  },
  {
    "title": "Hair Dryer",
    "slug": "hair-dryer",
    "url": "/hair-dryer.html",
    "group": "Personal Care",
    "cardTitle": "The hair dryer that makes the most sense",
    "decision": "T3 AireLuxe",
    "image": "/t3-aireluxe.png",
    "imageAlt": "T3 AireLuxe",
    "summary": "The best hair dryer for most people: controlled drying, easier daily use, and a stronger ownership case than cheap dryers or luxury systems.",
    "proof": "balanced reliability, comfort, control, and value make it more defensible than cheap dryers and less excessive than Dyson-level pricing.",
    "price": "Typical price: $180–$250",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $180–$250",
    "featuredQuote": "“The best hair dryer for most people: T3 AireLuxe — controlled drying, daily comfort, and practical premium ownership without Dyson-level pricing.”",
    "featuredProof": "<strong>Why it wins:</strong> balanced reliability, comfort, control, and value make it more defensible than cheap dryers and less excessive than luxury systems."
  },
  {
    "title": "Hair Straightener",
    "slug": "hair-straightener",
    "url": "/hair-straightener.html",
    "group": "Personal Care",
    "cardTitle": "The hair straightener that makes the most sense",
    "decision": "T3 SinglePass StyleMax 1”",
    "image": "/T3-SinglePass-StyleMax-Professional-1.webp",
    "imageAlt": "T3 SinglePass StyleMax 1 inch",
    "summary": "The best hair straightener for most people: controlled heat, smooth styling, broad everyday usability, and a stronger ownership case than cheaper tools.",
    "proof": "balanced reliability, controlled heat, and ease of use make it more defensible than cheap flat irons and less excessive than luxury tools.",
    "price": "Typical price: $180–$250",
    "featured": true,
    "featuredSub": "Personal Care · Typical price: $180–$250",
    "featuredQuote": "“The best hair straightener for most people: T3 SinglePass StyleMax 1” — controlled heat, smooth styling, and practical everyday ownership.”",
    "featuredProof": "<strong>Why it wins:</strong> balanced reliability, controlled heat, and ease of use make it more defensible than cheap flat irons and less excessive than luxury tools."
  }
];
